version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: user-service-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
 # Database migration service
  flyway-users:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./migration/sql:/flyway/sql
      - ./migration/flyway.conf:/flyway/conf/flyway.conf
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres
    networks:
      - user-service-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  user-service-network:
    driver: bridge
