version: '3.9'

services:
  postgress:
    image: postgres
    container_name: user-service-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: admin  

volumes:
      postgres_data:
        driver: local

networks:
  user-service-network:
    driver: bridge
    