apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  PG_USER: {{ .Values.postgres.user | quote }}
  PG_PASSWORD: {{ .Values.postgres.password | quote }}